#Coded by Philip Simonson. (AKA DevCool)

OBJS=Main.o Application.o Camera.o
EXECUTABLE=mygame.exe
CC=i686-w64-mingw32-g++ -g
CXX=$(CC)
CFLAGS=-std=c++11 -O2 -Wall -g
CXXFLAGS=$(CFLAGS)
LD=$(CXX)

all: $(EXECUTABLE) clean

rebuild: cleanest $(EXECUTABLE)

$(EXECUTABLE): $(OBJS)
	$(LD) $(CFLAGS) $(OBJS) -o $@ -mwindows -lmingw32 -lopengl32 -lglu32 -lSDLmain -lSDL

clean:
	@echo Cleaning up...
	@rm *.o
	@echo Done.

cleanest:
	@rm $(EXECUTABLE)
