#Coded by Philip Simonson. (AKA DevCool)

OBJS=Main.o Application.o Camera.o ObjLoader.o ResourceManager.o
EXECUTABLE=mygame.exe
CC=i686-w64-mingw32-g++
CXX=$(CC)
CFLAGS=-std=c++11 -O2 -Wall
CXXFLAGS=$(CFLAGS)
LD=$(CXX)

all: $(EXECUTABLE)

rebuild: clean all

$(EXECUTABLE): $(OBJS)
	$(LD) $(CFLAGS) $(OBJS) -o $@ -mwindows -lmingw32 -lSDLmain -lSDL -lopengl32 -lglu32

clean:
	@echo Cleaning up...
	@rm *.o $(EXECUTABLE)
	@echo Done.

